local mongodb using docker-container
HobbyTaste/frontend pull request #14
Opened 2020-03-04 17:11 UTC by SNVC1

2020-03-05 10:34 UTC, NikitaSikalov requested changes
Скрипт нужно перенести в `tasks`. В этой директории будут лежать все подобные служебные скрипты.
Также при запуске сервера пишется много лишней информации, предлагаю все в /dev/null и выводить только важную информацию типа:
```settings up DB....```
```Running server...```

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +container=hobbytaste_mongodb
Здесь лучше написать название переменной в скрипте большими буквами: `CONTAINER=<name>` и сделать пропуск строки

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +sudo docker stop ${container}
У меня вылетает здесь ошибка, хоть она и не мешает, но все равно выглядит не очень. Вообще контейнер не нужно стопить, ты же его стопишь в конце

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +#!/bin/bash
Давай сделаем `chmod a+x start-watch`, а сам start-watch.sh -> start-watch сделаем, тогда можно будет запускать вот так: `./start-watch`.

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +sudo docker rm ${container}
Давай не будем удалять контейнер, а лучше будем его запускать если локально он уже есть. Тогда не придется ниже пулить образ mongo и будет быстрее запускать сам скрипт

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +trap 'sudo docker stop ${container} > /dev/null && sudo docker rm ${container} > /dev/null' EXIT
как и писал выше - давай не будем удалять контейнер + вот эту всю логику тоже нужно выделить в отдельный скрипт `cleanup`

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +trap 'exit 1' INT TERM QUIT HUP
Это для чего здесь?

2020-03-05 10:34 UTC, NikitaSikalov commented on start-watch.sh
> +sudo docker pull mongo && sudo docker run -dp 27017:27017 --name ${container} mongo &&
Зачем писать команды через `&&` когда уже отдельно выделили целый скрипт на это. Нужно писать это на разных строчках.

2020-03-05 15:34 UTC, SNVC1 commented on start-watch.sh
> +sudo docker pull mongo && sudo docker run -dp 27017:27017 --name ${container} mongo &&
ну вообще назначение && отличается от слияния нескольких строк в одну

2020-03-06 06:53 UTC, NikitaSikalov requested changes
1. По-прежнему в консоли выводится лишняя инфа при запуске:
![image](https://user-images.githubusercontent.com/26010836/76057404-80d83500-5f8a-11ea-93be-8e14c70cd819.png)
+ теперь не поступает никаких сообщений от сервера, что вообще не ок, так как он логирует все запросы в консоль
2. Также при попытке запуска сервера, так как ты запускаешь из-под sudo требуется вводить пароль: это очень неудобно. Нужно сделать без sudo (для этого на ubuntu нужно правильно настроить права на запуск docker-демона и написать об этом readme.md для остальных ребят, чтобы была возможность у них запускать docker без sudo)

2020-03-06 12:12 UTC, NikitaSikalov approved these changes
Отличная работа, вроде все работает. От меня ок, только посмотри оставшиеся комменты

2020-03-06 12:12 UTC, NikitaSikalov commented on tasks/cleanup
> +echo "Stopping DB..."
Убери логи после завершения процесса и будет ок

2020-03-06 12:12 UTC, NikitaSikalov commented on tasks/cleanup
> +echo "success"
Тут тоже убрать

2020-03-06 12:12 UTC, NikitaSikalov commented on tasks/start-watch
> +	echo $CONTAINER
зачем выводить запущенный контейнер? Если уж выводишь, то пропиши что-то типо такого:
```
echo DB container $CONTAINER
```

2020-03-07 07:28 UTC, makut commented
Так, у меня все работает. Написал какие-то минорные вещи.

2020-03-07 17:28 UTC, makut commented on tasks/start-watch
> +if ! docker start $CONTAINER 2>/dev/null
А зачем выводить в /dev/null? Может быть, в логах будет полезная информация.

2020-03-07 17:28 UTC, makut commented on tasks/start-watch
> +NODE_APP_INSTANCE=secrets NODE_ENV=development ts-node-dev --project server/tsconfig.json --clear --respawn --transpileOnly ./server/app.ts
Может, еще добавить флаг --debug? Думаю, при локальной разработке лишним не будет.

2020-03-08 08:59 UTC, NikitaSikalov commented on tasks/start-watch
> +if ! docker start $CONTAINER 2>/dev/null
Да, действительно тут стоить продумать случай когда хочется запустить в полными логами запуска. Обычно это делается через какую-нибудь переменную окружения вот так: `LOG_LEVEL=debug`. Но пока мне кажется это не критично именно в этом скрипте. Если стрельнет, то сделаем

2020-03-08 09:00 UTC, NikitaSikalov commented on tasks/start-watch
> +NODE_APP_INSTANCE=secrets NODE_ENV=development ts-node-dev --project server/tsconfig.json --clear --respawn --transpileOnly ./server/app.ts
Думаю то же, что и выше

2020-03-08 09:01 UTC, makut commented on tasks/start-watch
> +if ! docker start $CONTAINER 2>/dev/null
Может просто записывать куда-нибудь в отдельную директорию логи по умолчанию, не в консоль?

2020-03-08 09:48 UTC, makut approved these changes

2020-03-09 20:25 UTC, merged