[HT-2] Dockerfile for server added
HobbyTaste/frontend pull request #15
Opened 2020-03-07 07:00 UTC by makut

Dockerfile для поднятия образа сервера на проде

2020-03-07 08:31 UTC, NikitaSikalov requested changes

2020-03-07 08:31 UTC, NikitaSikalov commented on README.md
> +## Запуск докера для запуска на production
Добавь этот пункт в содержание документа и ссылку на него

2020-03-07 08:31 UTC, NikitaSikalov commented on Dockerfile
> +COPY . .
Так делать не оптимально. Ты не пользуешься возможностями слоев докер образа. В данном случае сначала стоит скопировать `package.json` файл -> установить зависимости и только потом копировать весь проект и собирать его. Иначе получится, что ты каждый раз будешь впустую подтягивать зависимости, даже если не поменялись, а мог бы воспользоваться кэшированием слоев.

2020-03-08 08:55 UTC, NikitaSikalov requested changes

2020-03-08 08:55 UTC, NikitaSikalov commented on Dockerfile
> +COPY . .
Нужно копировать не все прям из папки, а только действительно важные вещи для проекта. Например если сейчас у меня установлены зависимости, то контекст разрастается и он будет еще и их копировать, что не нужно, ведь зависимости мы уже установили на предыдущем шаге. 
Я бы копировал только определенные папки, либо заносил в `.dockerignore` такие вещи как `node_modules`.

2020-03-15 13:34 UTC, NikitaSikalov approved these changes

2020-03-15 20:27 UTC, SNVC1 approved these changes

2020-03-16 20:29 UTC, merged