[HT-5] Added integration tests for backend
HobbyTaste/frontend pull request #22
Opened 2020-03-30 00:13 UTC by alexicon33

Задача: http://jira.prac.atp-fivt.org:8080/browse/HT-5
Добавил тесты и Readme с "документацией".

2020-03-30 18:56 UTC, NikitaSikalov requested changes

2020-03-30 18:56 UTC, NikitaSikalov commented on server/app.ts
> +  console.error = () => {};
А это еще зачем?

2020-03-30 18:56 UTC, NikitaSikalov commented on server/test/sample_data.ts
> +import { IProvider } from './../models/provider';
Это здорово что ты это написал, но Игнат как раз сделал задачу по добавлению фикстур данных в PR: https://github.com/HobbyTaste/web-application/pull/18. Тебе нужно синтегрировать эту систему в свой процесс тестирования

2020-03-30 18:56 UTC, NikitaSikalov commented on server/test/test.ts
> +        Hobby.deleteMany({}, (err: Error) => {
Лучше писать не через колбэки, а через `async` и `await`. Так было бы более понятно.

2020-03-30 18:56 UTC, NikitaSikalov commented on config/test.yaml
> +secrets:
Убираем, спроси у @SNVC1  про то как использовать БД из докер-контейнера для тестирования с предзаданными фикстурами

2020-03-30 18:56 UTC, NikitaSikalov commented on .mocharc.json
> +  "spec": "server/test/test.ts",
У нас же будет не один файл с тестами

2020-03-30 18:56 UTC, NikitaSikalov commented on package.json
> +    "async": "^3.2.0",
Зачем?

2020-03-30 18:56 UTC, NikitaSikalov commented on package.json
> +    "mongo": "PATH=~/Mongo/mongodb-shell-linux-x86_64-ubuntu1804-4.2.2/mongodb-linux-x86_64-ubuntu1804-4.2.2/bin mongo \"mongodb+srv://hobbytaste-a3rpe.mongodb.net/test\"  --username sikalov",
Это строчку не надо менять, ее вообще желательно было бы убрать

2020-03-30 18:56 UTC, NikitaSikalov commented on package.json
> +    "test": "NODE_ENV=test env TS_NODE_PROJECT='server/tsconfig.json' mocha --exit"
А `NODE_ENV` почему слева от env?

2020-03-30 18:56 UTC, NikitaSikalov commented on server/app.ts
> +  console.error = () => {};
Вместо этого у нас есть линтер, в котором ты можешь настроить правила.

2020-03-30 18:56 UTC, NikitaSikalov commented on server/app.ts
> +// for testing
кажется комментарий этот не нужен

2020-03-30 18:56 UTC, NikitaSikalov commented on server/app.ts
> +           logger.info(`Connect to mongoDB: success`)
И что, так критично будет если при тестировании это сообщение вылезет?

2020-03-30 18:56 UTC, NikitaSikalov commented on server/test/README.md
> +- В файле `test.ts` описаны сами тесты;
Файлов должно предполагаться несколько, а не один

2020-03-30 18:56 UTC, NikitaSikalov commented on server/test/README.md
> +- Файл `sample_data.ts` хранит маленький набор тестовых данных, использующихся для проверки работы контроллеров: 2 партнёра, 2 пользователя, 6 хобби и данные для обновления записей.
Опять же нужно связаться с @SNVC1

2020-03-30 18:56 UTC, NikitaSikalov commented on server/test/test.ts
> +describe('Sample Group', function() {
Тест просто огроменный - его точно нужно разбить на несколько describe и файлов

2020-03-30 19:20 UTC, alexicon33 commented on server/app.ts
> +           logger.info(`Connect to mongoDB: success`)
Нет, просто мне это кажется некрасивым: если условие убрать, сначала выводится название первой группы тестов, потом это сообщение, а потом логи первого теста.

2020-03-30 19:28 UTC, alexicon33 commented on package.json
> +    "async": "^3.2.0",
В некоторых тестах мне надо было выполнить несколько асинхронных запросов к базе данных, а именно: запустить их, подождать, пока они все выполнятся, и только потом вызвать done(). В async ровно для этого есть метод parallel, который я и использовал.

2020-03-30 20:44 UTC, alexicon33 commented on server/app.ts
> +  console.error = () => {};
Это для красоты: иначе между логами тестов выводятся всякие `deprecationWarning`-и самой `node.js` и левые `console.log`-и backend'a (оставлены они там не мной:) )
Про линтер не понял. (Я не хочу убирать console.log-и из кода, я просто не хочу, чтобы они выводились, когда `NODE_ENV === test`, а при разработке пусть выводятся)

2020-04-05 11:07 UTC, alexicon33 commented on server/test/sample_data.ts
> +import { IProvider } from './../models/provider';
Я посмотрел, как у Игната сделаны фикстуры, но кажется, это не совсем то, что мне нужно. 
1) Библиотека `node-mongodb-fixtures`, которую он использовал, не очень дружит с typescript'ом — в ней в принципе нет файлов описания/объявления типов. 
2) Там, мягко говоря, довольно ограниченный набор действий: есть методы unload и load, удаляющие сразу все фикстуры из базы или загружающие их в неё с какой-то предобработкой. 
3) Они мне не очень нужны: мне не нужно ничего предварительно загружать в базу данных, наоборот, нужно, чтобы перед каждой группой тестов все коллекции были пустыми, а уж потом я буду сам посылать отдельные json'ы к бэкенду и смотреть, что там в базе появляется. Поэтому фикстуры я использовал только для очистки коллекций перед тестами.

2020-04-06 19:31 UTC, NikitaSikalov requested changes

2020-04-06 19:31 UTC, NikitaSikalov commented on package.json
> +    "async": "^3.2.0",
А почему промисы не подошли?

2020-04-06 19:31 UTC, NikitaSikalov commented on server/app.ts
> +  console.error = () => {};
Ну тогда перенаправляй выводы нативным `> /dev/null`  при запуске команды

2020-04-06 19:31 UTC, NikitaSikalov commented on server/app.ts
> +           logger.info(`Connect to mongoDB: success`)
Лучше вообще убери эту строчку кода

2020-04-06 19:31 UTC, NikitaSikalov commented on server/app.ts
> +export const store = new MongoStore({
Перенеси это непосредственно в то место, где ты используешь это (то есть где импортируешь)

2020-04-06 19:31 UTC, NikitaSikalov commented on server/test/README.md
> +- Сами тесты описаны в файлах, начинающихся со слова "test". Сейчас их 3: `test_provider.ts`, `test_user.ts` и `test_hobby.ts`, в каждом из них описана соответствующая группа тестов.
Обычно делают вот такие файлы: `<name of test>.test.ts`

2020-04-06 19:31 UTC, NikitaSikalov commented on server/test/sample_data.ts
> +import { IProvider } from './../models/provider';
1. Тебе и не нужно, чтобы эта библиотека дружила с `ts`. Тебе достаточно выполнять команду заливки фикстур перед каждым тестом в хуке `beforeEach`. Поможет запускать консольные команды из ts кода библиотека `shelljs`.
2. А каких методов тебе еще не хватает? Кажется Игнат должен был создать удобную инфраструктура для наливки нужных фикстур и данных в БД. Этим нужно пользоваться
3. Как я и писал в первом пункте, ты можешь вызывать наливку фикстур прям из кода тестов, так что не вижу с этим проблем.
Самое главное почему стоит пользоваться решением Игната, потому что мы будем поддерживать унифицированное решение одно.

2020-04-06 19:31 UTC, NikitaSikalov commented on server/test/test_hobby.ts
> +            .then(() => utils.fixtures.unload())
лучше писать в нотации `async/await` - так более удобно и читабельно

2020-04-06 19:31 UTC, NikitaSikalov commented on server/test/test_provider.ts
> +        });
`await Promise.all(data.hobbies.map(utils.create_hooby_adder)` - и всего одна строчка и async не нужен

2020-04-06 20:57 UTC, alexicon33 commented on server/app.ts
> +  console.error = () => {};
Тогда не будет выводиться совсем ничего, а результаты тестов хотелось бы видеть.

2020-04-12 08:32 UTC, NikitaSikalov approved these changes

2020-04-12 10:05 UTC, merged